# Generated by Django 4.2.1 on 2023-05-30 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0002_alter_resrvation_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resrvation',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightapp.passenger'),
        ),
    ]
